---
AWSTemplateFormatVersion: 2010-09-09

Description: loadbalanced service

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '8080'
        CidrIp: '0.0.0.0/0'

  EC2InstanceV1:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        # THIS MUST BE NAMED DEFAULT
        default:
          packages:
            yum:
              - git
              - golang

    Properties:
      InstanceType: 't2.large'
      SecurityGroups: [!Ref 'WebServerSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: 'ami-0841edc20334f9287'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Install the files and packages from the metadata
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2InstanceV1 --region ${AWS::Region}
          git clone https://github.com/Nickhil-Sethi/vigilant-robot.git /home/ec2-user

Outputs:
  Name:
    Description: Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name

  EC2Endpoint:
    Description: EC2 server's endpoint
    Value: !GetAtt EC2InstanceV1.PublicDnsName
