AWSTemplateFormatVersion: 2010-09-09

Description: loadbalanced service

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '8080'
        CidrIp: '0.0.0.0/0'

  LaunchConfig:
    Type: AWS::EC2::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            git: []
            golang: []

    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: String
      InstanceMonitoring: Boolean
      KernelId: String
      LaunchConfigurationName: String
      PlacementTenancy: String
      RamDiskId: String
      SpotPrice: String
      InstanceType: 't2.large'
      SecurityGroups: [!Ref 'WebServerSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: 'ami-0841edc20334f9287'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Install the files and packages from the metadata
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2InstanceV9 --region ${AWS::Region}
          iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 8080
          cd /home/ec2-user; git clone https://github.com/Nickhil-Sethi/vigilant-robot.git
          su ec2-user; export HOME=/home/ec2-user
          cd vigilant-robot/; go build -o bin ./hello-world/; ./bin
Outputs:
  Name:
    Description: Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name

  EC2Endpoint:
    Description: EC2 server's endpoint
    Value: !GetAtt EC2InstanceV9.PublicDnsName
